name: ci.yml
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --no-daemon build
      - name: Render PUML with Docker
        run: |
          ls -la "${{ github.workspace }}/docs/content/diagrams"   # sanity check
          docker run --rm \
            -v "${{ github.workspace }}/docs/content/diagrams:/workspace" \
            -w /workspace \
            plantuml/plantuml:latest \
            -tpng -tsvg *.puml
      - name: Summarize JUnit results
        uses: test-summary/action@v2
        if: ${{ always() }}
        with:
          paths: |
            **/build/test-results/test/*.xml        # Gradle (JUnit)
